"""Climb00 keyframe-prediction and trajectory-infilling contracts."""

from .contact_q_generator import (
    ContactPlanQInfiller,
    ContactQPrediction,
    ContactTransitionPlan,
    SequentialContactQPredictor,
)
from .contracts import BODY_NAMES, CONTACT_BODY_INDEX, CONTACT_PARTS, InteractionBoundary, SparseKeyframe, TeacherSegment
from .fullbody import (
    ConstrainedKeypointResult,
    FullBodyCollisionAudit,
    FullBodyTeacherSegment,
    FullBodyTrajectory,
    KeypointTrajectory,
)
from .mechanical import G1MechanicalProjector, MechanicalConstraintError, MechanicallyConstrainedInfiller
from .neural_infiller import (
    CanonicalG1CollisionPoints,
    CanonicalG1ForwardKinematics,
    ContactAwareQInfillerLoss,
    G1ActionMedoidQDeformer,
    G1ConstrainedKeypointInfiller,
    G1ContactAwareQInfiller,
    InfillerLoss,
    InfillerOutput,
    constrained_infiller_loss,
    contact_aware_q_infiller_loss,
    full_geometry_box_collision_penalty,
    full_geometry_box_ground_penetration,
    full_geometry_box_penetration,
    full_geometry_contact_surface_penalty,
)
from .teacher_data import TeacherDataset
from .unified_interaction import (
    InteractionInfillerLoss,
    InteractionProjectionResult,
    InteractionQInfiller,
    UnifiedInteractionLoss,
    UnifiedInteractionPrediction,
    UnifiedInteractionPredictor,
    contact_rotation_losses,
    interaction_infiller_loss,
    project_interaction_q_trajectory,
    rollout_dense_collision_loss,
    rollout_ground_collision_loss,
    unified_interaction_loss,
)

__all__ = [
    "BODY_NAMES",
    "CONTACT_PARTS",
    "CONTACT_BODY_INDEX",
    "CanonicalG1CollisionPoints",
    "CanonicalG1ForwardKinematics",
    "ConstrainedKeypointResult",
    "ContactAwareQInfillerLoss",
    "ContactPlanQInfiller",
    "ContactQPrediction",
    "ContactTransitionPlan",
    "InteractionBoundary",
    "InteractionInfillerLoss",
    "InteractionProjectionResult",
    "InteractionQInfiller",
    "FullBodyCollisionAudit",
    "FullBodyTeacherSegment",
    "FullBodyTrajectory",
    "G1ActionMedoidQDeformer",
    "G1ConstrainedKeypointInfiller",
    "G1ContactAwareQInfiller",
    "G1MechanicalProjector",
    "InfillerLoss",
    "InfillerOutput",
    "KeypointTrajectory",
    "MechanicalConstraintError",
    "MechanicallyConstrainedInfiller",
    "SequentialContactQPredictor",
    "SparseKeyframe",
    "TeacherDataset",
    "TeacherSegment",
    "UnifiedInteractionLoss",
    "UnifiedInteractionPrediction",
    "UnifiedInteractionPredictor",
    "contact_rotation_losses",
    "constrained_infiller_loss",
    "contact_aware_q_infiller_loss",
    "full_geometry_box_collision_penalty",
    "full_geometry_box_ground_penetration",
    "full_geometry_box_penetration",
    "full_geometry_contact_surface_penalty",
    "interaction_infiller_loss",
    "project_interaction_q_trajectory",
    "rollout_dense_collision_loss",
    "rollout_ground_collision_loss",
    "unified_interaction_loss",
]
